[package]
name = "remote_call"
version = "0.1.0"
edition.workspace = true
description = "A Holochain coordinator zome for remote calls"
publish = false

[lib]
name = "remote_call_coordinator"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
hdk = { workspace = true }
remote_call_integrity = { workspace = true }

[lints]
workspace = true
