[package]
name = "return_single_value"
version = "0.1.0"
edition.workspace = true
description = "A Holochain zome with a single zome function 'get_value' that returns 5"
publish = false

[lib]
name = "return_single_value_coordinator"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
hdk = { workspace = true }

[lints]
workspace = true
