[package]
name = "path_validated"
version = "0.1.0"
edition.workspace = true
description = "A Holochain coordinator zome with path validation"
publish = false

[lib]
name = "path_validated_coordinator"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
hdk = { workspace = true }
path_validated_integrity = { workspace = true }

[lints]
workspace = true
