[package]
name = "two_party_countersigning"
version = "0.3.0-dev.1"
edition = "2021"
build = "../scenario_build.rs"

[dependencies]
anyhow = { workspace = true }
tokio = { workspace = true }
rand = { workspace = true }
log = { workspace = true }

holochain_types = { workspace = true }
holochain_wind_tunnel_runner = { workspace = true }
countersigning_integrity = { workspace = true }

[build-dependencies]
happ_builder = { workspace = true }

[lints]
workspace = true

[package.metadata.required-dna]
name = "countersigning"
zomes = ["countersigning"]

[package.metadata.required-happ]
name = "countersigning"
dnas = ["countersigning"]
