danger_generate_throwaway_device_seed: true
dpki:
  dna_path: ~
  network_seed: wind-tunnel-test
  allow_throwaway_random_dpki_agent_key: true
  no_dpki: false
network:
  network_type: quic_bootstrap
  transport_pool:
    - type: webrtc
      signal_url: "ws://localhost:4423"
  bootstrap_service: "http://localhost:4422"
tuning_params:
  countersigning_resolution_retry_delay:
    secs: 10
    nanos: 0
  countersigning_resolution_retry_limit: 5
