network:
  network_type: quic_bootstrap
  transport_pool:
    - type: webrtc
      signal_url: "ws://localhost:4423"
  bootstrap_service: "http://localhost:4422"
dpki:
  dna_path: ~
  no_dpki: true
  network_seed: ~
  device_seed_lair_tag: ~

