network:
  network_type: quic_bootstrap
  transport_pool:
    - type: webrtc
      signal_url: "wss://sbd.holo.host"
  bootstrap_service: "https://bootstrap.holo.host"
chc_url: "http://127.0.0.1:8181"