[package]
name = "zome_call_single_value"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
holochain_wind_tunnel_runner = { workspace = true }

[lints]
workspace = true
