[package]
name = "zome_call_single_value"
version = "0.1.0"
edition.workspace = true
build = "../scenario_build.rs"
publish = false

[dependencies]
holochain_wind_tunnel_runner = { workspace = true }

[build-dependencies]
happ_builder = { workspace = true }

[lints]
workspace = true

[package.metadata.required-dna]
name = "return_single_value"
zomes = ["return_single_value"]

[package.metadata.required-happ]
name = "return_single_value"
dnas = ["return_single_value"]
