[package]
name = "agent_activity"
version = "0.1.0"
edition.workspace = true
description = "A Holochain coordinator zome that gets agent activity"
publish = false

[lib]
name = "agent_activity_coordinator"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
hdk = { workspace = true }
agent_activity_integrity = { workspace = true }

[lints]
workspace = true
