# All options here https://docs.influxdata.com/influxdb/v2/reference/config-options/

e2e-testing: true # Allows clearing stores between tests.
http-bind-address: ":8087"
reporting-disabled: true # Don't send telemetry back to Influx
storage-validate-keys: true
