[package]
name = "validated_integrity"
version = "0.1.0"
edition = "2021"
description = "A Holochain integrity zome with validation"

[lib]
name = "validated_integrity"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
hdi = { workspace = true }
serde = { workspace = true }

[lints]
workspace = true
