[package]
name = "validated_integrity"
version = "0.1.0"
edition.workspace = true
description = "A Holochain integrity zome with validation"
publish = false

[lib]
name = "validated_integrity"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
hdi = { workspace = true }
holochain_serialized_bytes = { workspace = true }
serde = { workspace = true }

[lints]
workspace = true
