[package]
name = "write_read"
version = "0.1.0"
edition.workspace = true
build = "../scenario_build.rs"
publish = false

[dependencies]
holochain_types = { workspace = true }
holochain_wind_tunnel_runner = { workspace = true }

[build-dependencies]
happ_builder = { workspace = true }

[lints]
workspace = true

[package.metadata.required-dna]
name = "crud"
zomes = ["crud"]

[package.metadata.required-happ]
name = "crud"
dnas = ["crud"]
