[package]
name = "wind_tunnel_instruments"
version = "0.1.0"
edition = "2021"

[dependencies]
opentelemetry_api = { workspace = true }
anyhow = { workspace = true }
parking_lot = { workspace = true }
itertools = { workspace = true }

[lints]
workspace = true
