[package]
name = "wind_tunnel_instruments"
version = "0.1.0"
edition = "2021"

[dependencies]
opentelemetry_api = { workspace = true }
parking_lot = { workspace = true }
tabled = { workspace = true }

[lints]
workspace = true
