[package]
name = "timed"
version = "0.1.0"
edition.workspace = true
description = "A Holochain coordinator zome for timing data visiblity"
publish = false

[lib]
name = "timed_coordinator"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
hdk = { workspace = true }
timed_integrity = { workspace = true }

[lints]
workspace = true
