[package]
name = "holochain_client_instrumented"
version = "0.1.0"
edition = "2021"
description = "An instrumented wrapper around the holochain_client"

[dependencies]
anyhow = { workspace = true }

wind_tunnel_instruments = { workspace = true }
wind_tunnel_instruments_derive = { workspace = true }

holochain_client = { workspace = true }
holochain_zome_types = { workspace = true }
holo_hash = { workspace = true }
holochain_types = { workspace = true }
holochain_conductor_api = { workspace = true }

[lints]
workspace = true
