[package]
name = "validated_must_get_agent_activity_integrity"
version = "0.1.0"
edition.workspace = true
description = "A Holochain integrity zome with validation that calls must_get_agent_activity"
publish = false

[lib]
name = "validated_must_get_agent_activity_integrity"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
hdi = { workspace = true }
holochain_serialized_bytes = { workspace = true }
serde = { workspace = true }

[lints]
workspace = true
