[package]
name = "unyt_swap"
version = "0.1.0"
edition.workspace = true
build = "../scenario_build.rs"
publish = false

[dependencies]
anyhow = { workspace = true }
holochain_types = { workspace = true }
holochain_wind_tunnel_runner = { workspace = true }
log = { workspace = true }
rave_engine = { workspace = true }
rmp-serde = { workspace = true }
semver = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
wind_tunnel_unyt_scenario = { workspace = true }
zfuel = { workspace = true }

[build-dependencies]
happ_builder = { workspace = true }

[lints]
workspace = true

[package.metadata.fetch-required-happ]
name = "unyt"
url = "https://github.com/unytco/unyt-sandbox/releases/download/v0.108.0/unyt.happ"
sha256 = "a835a8bbb9129e82df3d02b3b81fdb5cd77adf9dcb8ed6c50a41cb13062e6165"
