[package]
name = "crud"
version = "0.1.0"
edition.workspace = true
description = "A Holochain coordinator zome for CRUD"
publish = false

[lib]
name = "crud_coordinator"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
hdk = { workspace = true }
crud_integrity = { workspace = true }

[lints]
workspace = true
