[package]
name = "crud"
version = "0.1.0"
edition = "2021"
description = "A Holochain coordinator zome for CRUD"
build = "../../wasm_build.rs"

[lib]
name = "crud_coordinator"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
hdk = { workspace = true }
crud_integrity = { workspace = true }

[lints]
workspace = true
