[package]
name = "signal"
version = "0.1.0"
edition = "2021"
description = "A Holochain coordinator zome for emiting signals"

[lib]
name = "signal_coordinator"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
hdk = { workspace = true }

[lints]
workspace = true
