[package]
name = "remote_signal"
version = "0.1.0"
edition = "2021"
description = "A Holochain coordinator zome for remote signals"

[lib]
name = "remote_signal_coordinator"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
hdk = { workspace = true }
remote_signal_integrity = { workspace = true }

[lints]
workspace = true
