name: "cargo_update"

on:
  workflow_dispatch:
  schedule:
    # At 7:00am on Wednesday
    - cron: "0 7 * * 3"

jobs:
  flake_update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install nix
        uses: cachix/install-nix-action@v30
        with:
          install_url: https://releases.nixos.org/nix/nix-2.24.9/install

      - name: Flake update
        run: |
          nix develop .#ci --command cargo update

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: Update Cargo.lock"
          title: "Update Cargo.lock"
          body: "This PR updates the Cargo.lock file."
          branch: "update-cargo-lock"
          branch-suffix: "short-commit-hash"
          base: "main"
