name: "Nomad Post Processing"

on:
  workflow_call:
    inputs:
      holochain-bin-url:
        description: "The URL to download the `holochain` binary from"
        type: string
        required: true
      commit-hash:
        description: "The git commit hash to checkout before running the tests"
        type: string
        required: false
      enable-summary-uploads:
        description: "Enable upload of summary visualiser html to GitHub Pages and summary json to bucket"
        type: boolean
        required: true
      ignore-summary-errors:
        description: "Ignore errors from summarizer"
        type: boolean
        required: true
      matrix-step-name:
        description: "Matrix step name used for cloudposse matrix outputs"
        type: string
        required: true
    secrets:
      NOMAD_ACCESS_TOKEN:
        required: true
      INFLUX_TOKEN:
        required: true
      HETZNER_HOLOCHAIN_INFRA_BUCKETS_ACCESS:
        required: true
      HETZNER_HOLOCHAIN_INFRA_BUCKETS_SECRET:
        required: true
      CACHIX_AUTH_TOKEN:
        required: true

jobs:
  collect-github-matrix-outputs:
    name: Collect Run Ids
    runs-on: ubuntu-latest
    if: ${{ !cancelled() }}
    steps:
      - uses: cloudposse/github-action-matrix-outputs-read@v1
        id: read
        with:
          matrix-step-name: ${{ inputs.matrix-step-name }}

      - name: Restructure merged output
        id: restructure
        run: |
          echo '${{ steps.read.outputs.result }}' | jq -c -R 'fromjson |
            (.alloc_ids | keys) as $keys |
            [ $keys[] as $key |
              {
                job_name: .job_name[$key],
                run_id: .run_id[$key],
                started_at: .started_at[$key],
                duration: .duration[$key],
                alloc_ids: .alloc_ids[$key]
              }
            ]' > out.json

          echo "result=$(cat out.json)" >> $GITHUB_OUTPUT

    outputs:
      result: "${{ steps.restructure.outputs.result }}"

  wait-for-jobs:
    name: Wait for Nomad jobs to finish
    runs-on: ubuntu-latest
    needs: collect-github-matrix-outputs
    if: ${{ !cancelled() }}
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.collect-github-matrix-outputs.outputs.result) }}
    steps:
      - uses: actions/checkout@v6

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Setup cachix
        uses: cachix/cachix-action@v16
        with:
          name: holochain-ci
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Wait for all allocations in job
        env:
          NOMAD_ADDR: https://nomad-server-01.holochain.org:4646
          NOMAD_CACERT: "${{ github.workspace }}/nomad/server-ca-cert.pem"
          NOMAD_TOKEN: ${{ secrets.NOMAD_ACCESS_TOKEN }}
        run: |-
          # get started at
          started_at=${{ matrix.started_at }}
          duration=${{ matrix.duration }}
          current_time=$(date +%s)
          buffer=600
          # set timeout to $duration + $buffer (seconds $buffer) - ($current_time - $started_at)
          remaining=$(( duration - (current_time - started_at) ))
          export TIMEOUT=$(( $remaining + $buffer ))
          export TIMEOUT=$(( TIMEOUT < 0 ? $duration + $buffer : TIMEOUT )) # if timeout is negative; set to `duration + buffer`
          echo "Timeout for ${{ matrix.job_name }}: $TIMEOUT seconds (started_at: ${started_at}; duration: ${duration})"
          nix develop --command ./nomad/scripts/wait_for_jobs.sh ${{ matrix.job_name }} ${{ matrix.alloc_ids }}

  run-summary:
    name: Generate a summary of all scenarios
    runs-on: ubuntu-latest
    needs: wait-for-jobs
    if: ${{ !cancelled() }}
    steps:
      - uses: actions/checkout@v6

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Setup cachix
        uses: cachix/cachix-action@v16
        with:
          name: holochain-ci
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Download all alloc_ids
        uses: actions/download-artifact@v7
        with:
          pattern: "alloc_ids_*"

      - name: Combine alloc_ids files into single
        run: cat alloc_ids_*/alloc_ids.csv >> alloc_ids.csv

      - name: Prepare run summary
        env:
          NIXPKGS_ALLOW_UNFREE: 1
          NOMAD_ADDR: https://nomad-server-01.holochain.org:4646
          NOMAD_CACERT: "${{ github.workspace }}/nomad/server-ca-cert.pem"
          NOMAD_TOKEN: ${{ secrets.NOMAD_ACCESS_TOKEN }}
          RUN_SUMMARY_PATH: ./run_summary.jsonl
          HOLOCHAIN_BIN_URL: ${{ inputs.holochain-bin-url }}
        run: |
          nix develop --command ./nomad/scripts/ci_allocs.sh generate_run_summary alloc_ids.csv "$RUN_SUMMARY_PATH"
          cat "$RUN_SUMMARY_PATH" >> "$GITHUB_STEP_SUMMARY"

      - name: Cache summariser
        uses: actions/cache@v5
        with:
          path: |
            target/
            .cargo/registry
            .cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Run summariser
        if: ${{ !cancelled() }}
        env:
          INFLUX_HOST: "https://ifdb.holochain.org"
          INFLUX_BUCKET: "windtunnel"
          INFLUX_TOKEN: ${{ secrets.INFLUX_TOKEN }}
          RUST_LOG: debug
          IGNORE_SUMMARY_ERRORS: ${{ inputs.ignore-summary-errors }}
        run: nix develop --command cargo run --release --bin holochain-summariser

      - name: Generate summary id for artifacts
        id: generate-summary-id
        run: |
          SUMMARY_TIMESTAMP=$(date +%s)
          SUMMARY_ID="$(date -d @${SUMMARY_TIMESTAMP} '+%Y%m%d%H%M%S').${{ inputs.commit-hash || github.sha }}"
          echo "summary_timestamp=$SUMMARY_TIMESTAMP" >> "$GITHUB_OUTPUT"
          echo "summary_id=$SUMMARY_ID" >> "$GITHUB_OUTPUT"

      - name: Checkout latest runs list from GitHub Pages
        if: inputs.enable-summary-uploads
        uses: actions/checkout@v6
        with:
          ref: gh-pages
          path: site
          sparse-checkout: _includes/runs-list.md

      - name: Generate summary visualiser
        id: generate-summary-visualiser
        run: |
          mkdir -p ./site
          OUTPUT_FILE="run.${{ steps.generate-summary-id.outputs.summary_id }}.html"

          # The summary visualiser can only take one file at a time,
          # but only one summariser report JSON file is fed to it in a run.
          # The wildcard here is because we don't know the name of the file.
          nix run .#generate-summary-visualiser ./summariser-report-*.json "./site/${OUTPUT_FILE}"

          echo "output_file=${OUTPUT_FILE}" >> "$GITHUB_OUTPUT"

      - name: Add summary to runs list
        if: inputs.enable-summary-uploads
        run: |
          SUMMARY_TIMESTAMP_HUMAN="$(date -d @${{ steps.generate-summary-id.outputs.summary_timestamp }} '+%Y-%m-%d %H:%M:%S')"
          LIST_ITEM_STRING="- [${SUMMARY_TIMESTAMP_HUMAN} (${{ inputs.commit-hash || github.sha }})](${{ steps.generate-summary-visualiser.outputs.output_file }})"

          # Prepend to runs list
          sed -i "1i${LIST_ITEM_STRING}" ./site/_includes/runs-list.md

      - name: Push summary visualiser html and updated runs list to GitHub Pages
        if: inputs.enable-summary-uploads
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ github.token }}
          publish_dir: ./site/
          publish_branch: gh-pages
          keep_files: true
          enable_jekyll: true

      - name: Upload run summary to bucket
        if: inputs.enable-summary-uploads
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.HETZNER_HOLOCHAIN_INFRA_BUCKETS_ACCESS }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.HETZNER_HOLOCHAIN_INFRA_BUCKETS_SECRET }}
          AWS_DEFAULT_REGION: fsn1
          AWS_ENDPOINT_URL: https://fsn1.your-objectstorage.com
          S3_BUCKET_NAME: wind-tunnel-artifacts
        run: |-
          OUT_PATH="${S3_BUCKET_NAME}/summariser-reports/${{ steps.generate-summary-id.outputs.summary_id }}.json"
          nix run .#awscli-s3 cp summariser-report-*.json "s3://${OUT_PATH}"

          echo "Uploaded run summary to ${AWS_ENDPOINT_URL}/${OUT_PATH}" >> "$GITHUB_STEP_SUMMARY"

  cleanup:
    name: Cleanup scenario artifacts
    runs-on: ubuntu-latest
    needs: wait-for-jobs
    if: always()
    steps:
      - uses: actions/checkout@v6

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Setup cachix
        uses: cachix/cachix-action@v16
        with:
          name: holochain-ci
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Delete scenarios from bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.HETZNER_HOLOCHAIN_INFRA_BUCKETS_ACCESS }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.HETZNER_HOLOCHAIN_INFRA_BUCKETS_SECRET }}
          AWS_DEFAULT_REGION: hel1
          AWS_ENDPOINT_URL: https://hel1.your-objectstorage.com
          S3_BUCKET_NAME: wind-tunnel-public-artifacts
        run: |-
          nix run .#awscli-s3 -- rm "s3://${S3_BUCKET_NAME}/run-artifacts/${{ github.run_id }}" --recursive

          echo "Deleted ${AWS_ENDPOINT_URL}/${S3_BUCKET_NAME}/run-artifacts/${{ github.run_id }}" >> "$GITHUB_STEP_SUMMARY"
