name: "Run demo performance tests on Nomad cluster"

on:
  workflow_dispatch:
    inputs:
      holochain-bin-url:
        description: "The URL to download the `holochain` binary from"
        required: false
      commit-hash:
        description: "The commit hash to checkout before running the tests"
        required: false
      rebuild-all-scenarios:
        description: "Force a rebuild of all scenarios even if no relevant files have changed"
        type: boolean
        required: false
        default: false
  pull_request:
    paths:
      - ".github/workflows/nomad*.yaml"
      - ".github/actions/nomad/action.yaml"

concurrency:
  group: nomad # This is the same group as all other Nomad workflows
  cancel-in-progress: false

jobs:
  run-scenarios:
    name: Run Scenario ${{ matrix.job-name }}
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        job-name:
          - first_call
          - local_signals
          - remote_call_rate
          - remote_signals
          - single_write_many_read
          - write_query
          - write_read
          - write_validated
          - zome_call_single_value
          - app_install_large
          - app_install_minimal
          - dht_sync_lag
          - validation_receipts
          - write_get_agent_activity
          - write_get_agent_activity_volatile
          - write_validated_must_get_agent_activity
          - two_party_countersigning
          - zero_arc_create_data
          - zero_arc_create_data_validated
          - zero_arc_create_and_read
          - full_arc_create_validated_zero_arc_read
          - mixed_arc_get_agent_activity
          - mixed_arc_must_get_agent_activity
          # Temporarily disabled while Unyt app is not upgraded to Holochain v0.7.0
          # - unyt_chain_transaction
          # - unyt_chain_transaction_zero_arc
          # - unyt_proposal
    runs-on: ubuntu-latest
    timeout-minutes: 480
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.commit-hash || github.sha }}

      - uses: ./.github/actions/nomad
        with:
          nomad-access-token: ${{ secrets.NOMAD_ACCESS_TOKEN }}
          hetzner-buckets-access: ${{ secrets.HETZNER_HOLOCHAIN_INFRA_BUCKETS_ACCESS }}
          hetzner-buckets-secret: ${{ secrets.HETZNER_HOLOCHAIN_INFRA_BUCKETS_SECRET }}
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          job-name: ${{ matrix.job-name }}
          holochain-bin-url: ${{ inputs.holochain-bin-url != '' && inputs.holochain-bin-url || 'https://github.com/holochain/holochain/releases/download/holochain-0.7.0-rc.1/holochain-unstable-x86_64-unknown-linux-gnu' }}
          commit-hash: ${{ inputs.commit-hash }}
          nomad-job-variant-directory: "nomad/job-variants/demo"
          include-threefold-node-pool: "false"
          force-rebuild: ${{ inputs.rebuild-all-scenarios }}

  post-run-scenarios:
    needs: run-scenarios
    uses: ./.github/workflows/nomad-common-post.yaml
    if: ${{ always() }}
    secrets:
      NOMAD_ACCESS_TOKEN: ${{ secrets.NOMAD_ACCESS_TOKEN }}
      INFLUX_TOKEN: ${{ secrets.INFLUX_TOKEN }}
      HETZNER_HOLOCHAIN_INFRA_BUCKETS_ACCESS: ${{ secrets.HETZNER_HOLOCHAIN_INFRA_BUCKETS_ACCESS }}
      HETZNER_HOLOCHAIN_INFRA_BUCKETS_SECRET: ${{ secrets.HETZNER_HOLOCHAIN_INFRA_BUCKETS_SECRET }}
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
    with:
      holochain-bin-url: ${{ inputs.holochain-bin-url != '' && inputs.holochain-bin-url || 'https://github.com/holochain/holochain/releases/download/holochain-0.7.0-rc.1/holochain-unstable-x86_64-unknown-linux-gnu' }}
      commit-hash: ${{ inputs.commit-hash }}
      enable-summary-uploads: false
      ignore-summary-errors: false
