name: "Performance Tests"

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, wind-tunnel]
    steps:
      - uses: actions/checkout@v4

      - name: Smoke test - zome_call_single_value
        run: |
          # Start a sandbox conductor and run it in the background
          nix develop .#ci -c bash -c "hc s clean && echo "1234" | hc s --piped create && echo "1234" | hc s --piped -f 8888 run &"

          # Run the scenario for 5 seconds
          RUST_LOG=info nix run .#zome_call_single_value -- --connection-string ws://localhost:8888 --duration 5 --no-progress

          pkill hc && pkill holochain && pkill lair-keystore
