name: "Performance Tests"

on:
  workflow_dispatch:

env:
  INFLUX_TOKEN: ${{ secrets.INFLUX_TOKEN }}
  WT_METRICS_DIR: "${{ github.workspace }}/telegraf/metrics"

jobs:
  test:
    runs-on: [self-hosted, wind-tunnel]
    strategy:
      fail-fast: false
      matrix:
        scenario: [ zome_call_single_value ]
    steps:
      - uses: actions/checkout@v4

      - name: Smoke test - ${{ matrix.scenario }}
        run: |
          # Start a sandbox conductor and run it in the background
          nix develop .#ci -c bash -c "hc s clean && echo "1234" | hc s --piped create && echo "1234" | hc s --piped -f 8888 run &"

          RUST_LOG=info nix run .#${{ matrix.scenario }} -- --connection-string ws://localhost:8888 --duration 120 --no-progress --reporter influx-file

          pkill hc && pkill holochain && pkill lair-keystore

      - name: Run Telegraf to upload influx metrics
        run: nix run nixpkgs#telegraf -- --config telegraf/runner-telegraf.conf --once
