name: "Performance Tests"

on:
  workflow_dispatch:

env:
  INFLUX_TOKEN: ${{ secrets.INFLUX_TOKEN }}
  WT_METRICS_DIR: "${{ github.workspace }}/telegraf/metrics"

jobs:
  test:
    runs-on: [self-hosted, wind-tunnel]
    strategy:
      fail-fast: false
      matrix:
        scenario: [ zome_call_single_value, single_write_many_read, write_read, write_query, local_signals, write_validated ]
        include:
          - scenario: dht_sync_lag
            extra-args: "--agents 2 --behaviour write:1 --behaviour record_lag:1"
          - scenario: app_install
            extra-args: "--agents 2 --behaviour minimal:1 --behaviour large:1"
          - scenario: first_call
            extra-args: "--agents 1 --behaviour local:1"
    steps:
      - uses: actions/checkout@v4

      - name: Smoke test - ${{ matrix.scenario }}
        run: |
          # Start a sandbox conductor and run it in the background
          nix develop .#ci -c bash -c "hc s clean && echo "1234" | hc s --piped create && echo "1234" | hc s --piped -f 8888 run &"

          RUST_LOG=info nix run .#${{ matrix.scenario }} -- --connection-string ws://localhost:8888 --duration 120 --no-progress --reporter influx-file ${{ matrix.extra-args }}

          pkill hc && pkill holochain && pkill lair-keystore

      - name: Run Telegraf to upload influx metrics
        run: nix run nixpkgs#telegraf -- --config telegraf/runner-telegraf.conf --once

  trycp-test:
    runs-on: [self-hosted, wind-tunnel]
    strategy:
      fail-fast: false
      matrix:
        scenario: [ trycp_write_validated, remote_call_rate, validation_receipts ]
        include:
          - scenario: two_party_countersigning
            extra-args: "--behaviour initiate:1 --behaviour participate:1"
    steps:
      - uses: actions/checkout@v4

      - name: Smoke test - ${{ matrix.scenario }}
        run: |
          set -x

          # Start local network services
          nix develop .#ci -c bash -c "hc-run-local-services --bootstrap-port 4422 --signal-port 4423 &"
          # Start a TryCP instance
          nix develop .#ci -c bash -c "source ./scripts/trycp.sh && start_trycp &"

          RUST_LOG=warn CONDUCTOR_CONFIG="CI" MIN_PEERS=2 nix run .#${{ matrix.scenario }} -- --targets targets-ci.yaml --instances-per-target 2 --duration 120 --no-progress --reporter influx-file ${{ matrix.extra-args }}

          # Stop the TryCP instance
          nix develop .#ci -c bash -c "source ./scripts/trycp.sh && stop_trycp"
          # Stop local network services
          pkill hc-run-local

      - name: Run Telegraf to upload influx metrics
        run: nix run nixpkgs#telegraf -- --config telegraf/runner-telegraf.conf --once
