name: "Performance Tests"

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, wind-tunnel]
    steps:
      - uses: actions/checkout@v4

      - name: Smoke test - zome_call_single_value
        run: |
          # Start a sandbox conductor and run it in the background
          nix develop .#ci -c bash -c "hc s clean && echo "1234" | hc s --piped create && echo "1234" | hc s --piped -f 8888 run &"

          RUST_LOG=info nix run .#zome_call_single_value -- --connection-string ws://localhost:8888 --duration 120 --no-progress --reporter influx-file

          pkill hc && pkill holochain && pkill lair-keystore

      - name: Smoke test - single_write_many_read
        run: |
          # Start a sandbox conductor and run it in the background
          nix develop .#ci -c bash -c "hc s clean && echo "1234" | hc s --piped create && echo "1234" | hc s --piped -f 8888 run &"

          RUST_LOG=info nix run .#single_write_many_read -- --connection-string ws://localhost:8888 --duration 120 --no-progress --reporter influx-file

          pkill hc && pkill holochain && pkill lair-keystore

      - name: Smoke test - dht_sync_lag
        run: |
          # Start a sandbox conductor and run it in the background
          nix develop .#ci -c bash -c "hc s clean && echo "1234" | hc s --piped create && echo "1234" | hc s --piped -f 8888 run &"

          RUST_LOG=info nix run .#dht_sync_lag -- --connection-string ws://localhost:8888 --agents 2 --behaviour write:1 --behaviour record_lag:1 --duration 120 --no-progress --reporter influx-file

          pkill hc && pkill holochain && pkill lair-keystore

      - name: Smoke test - app_install
        run: |
          # Start a sandbox conductor and run it in the background
          nix develop .#ci -c bash -c "hc s clean && echo "1234" | hc s --piped create && echo "1234" | hc s --piped -f 8888 run &"

          RUST_LOG=info nix run .#app_install -- --connection-string ws://localhost:8888 --agents 2 --behaviour minimal:1 --behaviour large:1 --duration 120 --no-progress --reporter influx-file

          pkill hc && pkill holochain && pkill lair-keystore

      - name: Smoke test - first_call
        run: |
          # Start a sandbox conductor and run it in the background
          nix develop .#ci -c bash -c "hc s clean && echo "1234" | hc s --piped create && echo "1234" | hc s --piped -f 8888 run &"

          RUST_LOG=info nix run .#first_call -- --connection-string ws://localhost:8888 --agents 1 --behaviour local:1 --duration 120 --no-progress --reporter influx-file

          pkill hc && pkill holochain && pkill lair-keystore

      - name: Smoke test - write_read
        run: |
          # Start a sandbox conductor and run it in the background
          nix develop .#ci -c bash -c "hc s clean && echo "1234" | hc s --piped create && echo "1234" | hc s --piped -f 8888 run &"

          RUST_LOG=info nix run .#write_read -- --connection-string ws://localhost:8888 --duration 120 --no-progress --reporter influx-file

          pkill hc && pkill holochain && pkill lair-keystore

      - name: Smoke test - write_query
        run: |
          # Start a sandbox conductor and run it in the background
          nix develop .#ci -c bash -c "hc s clean && echo "1234" | hc s --piped create && echo "1234" | hc s --piped -f 8888 run &"

          RUST_LOG=info nix run .#write_query -- --connection-string ws://localhost:8888 --duration 120 --no-progress --reporter influx-file

          pkill hc && pkill holochain && pkill lair-keystore

      - name: Smoke test - local_signals
        run: |
          # Start a sandbox conductor and run it in the background
          nix develop .#ci -c bash -c "hc s clean && echo "1234" | hc s --piped create && echo "1234" | hc s --piped -f 8888 run &"

          RUST_LOG=info nix run .#local_signals -- --connection-string ws://localhost:8888 --duration 120 --no-progress --reporter influx-file

          pkill hc && pkill holochain && pkill lair-keystore

      - name: Smoke test - write_validated
        run: |
          # Start a sandbox conductor and run it in the background
          nix develop .#ci -c bash -c "hc s clean && echo "1234" | hc s --piped create && echo "1234" | hc s --piped -f 8888 run &"

          RUST_LOG=info nix run .#write_validated -- --connection-string ws://localhost:8888 --duration 120 --no-progress --reporter influx-file

          pkill hc && pkill holochain && pkill lair-keystore

      - name: Smoke test - trycp_write_validated
        run: |
          set -x

          # Start local network services
          nix develop .#ci -c bash -c "hc-run-local-services --bootstrap-port 4422 --signal-port 4423 &"
          # Start a TryCP instance
          nix develop .#ci -c bash -c "source ./scripts/trycp.sh && start_trycp &"

          RUST_LOG=warn CONDUCTOR_CONFIG="CI" MIN_PEERS=2 nix run .#trycp_write_validated -- --targets targets-ci.yaml --instances-per-target 2 --duration 120 --no-progress --reporter influx-file

          # Stop the TryCP instance
          nix develop .#ci -c bash -c "source ./scripts/trycp.sh && stop_trycp"
          # Stop local network services
          pkill hc-run-local

      - name: Smoke test - remote_call_rate
        run: |
          set -x

          # Start local network services
          nix develop .#ci -c bash -c "hc-run-local-services --bootstrap-port 4422 --signal-port 4423 &"
          # Start a TryCP instance
          nix develop .#ci -c bash -c "source ./scripts/trycp.sh && start_trycp &"

          RUST_LOG=warn CONDUCTOR_CONFIG="CI" MIN_PEERS=2 nix run .#remote_call_rate -- --targets targets-ci.yaml --instances-per-target 2 --duration 120 --no-progress --reporter influx-file

          # Stop the TryCP instance
          nix develop .#ci -c bash -c "source ./scripts/trycp.sh && stop_trycp"
          # Stop local network services
          pkill hc-run-local

      - name: Smoke test - two_party_countersigning
        run: |
          # Start local network services
          nix develop .#ci -c bash -c "hc-run-local-services --bootstrap-port 4422 --signal-port 4423 &"
          # Start a TryCP instance
          nix develop .#ci -c bash -c "source ./scripts/trycp.sh && start_trycp &"

          RUST_LOG=warn CONDUCTOR_CONFIG="CI" MIN_PEERS=2 nix run .#two_party_countersigning -- --targets targets-ci.yaml --behaviour initiate:1 --behaviour participate:1 --instances-per-target 2 --duration 120 --no-progress --reporter influx-file

          # Stop the TryCP instance
          nix develop .#ci -c bash -c "source ./scripts/trycp.sh && stop_trycp"
          # Stop local network services
          pkill hc-run-local

      - name: Smoke test - validation_receipts
        run: |
          set -x

          # Start local network services
          nix develop .#ci -c bash -c "hc-run-local-services --bootstrap-port 4422 --signal-port 4423 &"
          # Start a TryCP instance
          nix develop .#ci -c bash -c "source ./scripts/trycp.sh && start_trycp &"

          RUST_LOG=warn CONDUCTOR_CONFIG="CI" MIN_PEERS=2 nix run .#validation_receipts -- --targets targets-ci.yaml --instances-per-target 2 --duration 120 --no-progress --reporter influx-file

          # Stop the TryCP instance
          nix develop .#ci -c bash -c "source ./scripts/trycp.sh && stop_trycp"
          # Stop local network services
          pkill hc-run-local
