name: "Performance Tests"

on:
  workflow_dispatch:

env:
  INFLUX_TOKEN: ${{ secrets.INFLUX_TOKEN }}
  WT_METRICS_DIR: "${{ github.workspace }}/telegraf/metrics"

jobs:
  test:
    runs-on: [self-hosted, wind-tunnel]
    strategy:
      fail-fast: false
      matrix:
        scenario: [ zome_call_single_value, single_write_many_read, write_read, write_query, local_signals, write_validated ]
        include:
          - scenario: dht_sync_lag
            extra-args: "--agents 2 --behaviour write:1 --behaviour record_lag:1"
          - scenario: app_install
            extra-args: "--agents 2 --behaviour minimal:1 --behaviour large:1"
          - scenario: first_call
            extra-args: "--agents 1 --behaviour local:1"
    steps:
      - uses: actions/checkout@v4

      - name: Smoke test - ${{ matrix.scenario }}
        run: |
          # Start a sandbox conductor and run it in the background
          nix develop .#ci -c bash -c "hc s clean && echo "1234" | hc s --piped create && echo "1234" | hc s --piped -f 8888 run &"

          RUST_LOG=info nix run .#${{ matrix.scenario }} -- --connection-string ws://localhost:8888 --duration 120 --no-progress --reporter influx-file ${{ matrix.extra-args }}

          pkill hc && pkill holochain && pkill lair-keystore

      - name: Run Telegraf to upload influx metrics
        run: nix run nixpkgs#telegraf -- --config telegraf/runner-telegraf.conf --once
