name: "Performance Tests"

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, wind-tunnel]
    steps:
      - uses: actions/checkout@v4

      - name: Smoke test - zome_call_single_value
        run: |
          # Start a sandbox conductor and run it in the background
          nix develop .#ci -c bash -c "hc s clean && echo "1234" | hc s --piped create && echo "1234" | hc s --piped -f 8888 run &"

          # Run the scenario for 5 seconds
          RUST_LOG=info nix run .#zome_call_single_value -- --connection-string ws://localhost:8888 --duration 5 --no-progress --reporter influx-file

          pkill hc && pkill holochain && pkill lair-keystore

      - name: Smoke test - single_write_many_read
        run: |
          # Start a sandbox conductor and run it in the background
          nix develop .#ci -c bash -c "hc s clean && echo "1234" | hc s --piped create && echo "1234" | hc s --piped -f 8888 run &"

          # Run the scenario for 5 seconds
          RUST_LOG=info nix run .#single_write_many_read -- --connection-string ws://localhost:8888 --duration 5 --no-progress --reporter influx-file

          pkill hc && pkill holochain && pkill lair-keystore

      - name: Smoke test - dht_sync_lag
        run: |
          # Start a sandbox conductor and run it in the background
          nix develop .#ci -c bash -c "hc s clean && echo "1234" | hc s --piped create && echo "1234" | hc s --piped -f 8888 run &"

          # Run the scenario for 5 seconds
          RUST_LOG=info nix run .#dht_sync_lag -- --connection-string ws://localhost:8888 --agents 2 --behaviour write:1 --behaviour record_lag:1 --duration 5 --no-progress --reporter influx-file

          pkill hc && pkill holochain && pkill lair-keystore

      - name: Smoke test - app_install
        run: |
          # Start a sandbox conductor and run it in the background
          nix develop .#ci -c bash -c "hc s clean && echo "1234" | hc s --piped create && echo "1234" | hc s --piped -f 8888 run &"

          # Run the scenario for 5 seconds
          RUST_LOG=info nix run .#app_install -- --connection-string ws://localhost:8888 --agents 2 --behaviour minimal:1 --behaviour large:1 --duration 5 --no-progress --reporter influx-file

          pkill hc && pkill holochain && pkill lair-keystore

      - name: Smoke test - first_call
        run: |
          # Start a sandbox conductor and run it in the background
          nix develop .#ci -c bash -c "hc s clean && echo "1234" | hc s --piped create && echo "1234" | hc s --piped -f 8888 run &"

          # Run the scenario for 5 seconds
          RUST_LOG=info nix run .#first_call -- --connection-string ws://localhost:8888 --agents 1 --behaviour local:1 --duration 5 --no-progress --reporter influx-file

          pkill hc && pkill holochain && pkill lair-keystore

      - name: Smoke test - write_read
        run: |
          # Start a sandbox conductor and run it in the background
          nix develop .#ci -c bash -c "hc s clean && echo "1234" | hc s --piped create && echo "1234" | hc s --piped -f 8888 run &"

          # Run the scenario for 5 seconds
          RUST_LOG=info nix run .#write_read -- --connection-string ws://localhost:8888 --duration 5 --no-progress --reporter influx-file

          pkill hc && pkill holochain && pkill lair-keystore

      - name: Smoke test - write_query
        run: |
          # Start a sandbox conductor and run it in the background
          nix develop .#ci -c bash -c "hc s clean && echo "1234" | hc s --piped create && echo "1234" | hc s --piped -f 8888 run &"

          # Run the scenario for 5 seconds
          RUST_LOG=info nix run .#write_query -- --connection-string ws://localhost:8888 --duration 5 --no-progress --reporter influx-file

          pkill hc && pkill holochain && pkill lair-keystore

      - name: Smoke test - local_signals
        run: |
          # Start a sandbox conductor and run it in the background
          nix develop .#ci -c bash -c "hc s clean && echo "1234" | hc s --piped create && echo "1234" | hc s --piped -f 8888 run &"

          # Run the scenario for 5 seconds
          RUST_LOG=info nix run .#local_signals -- --connection-string ws://localhost:8888 --duration 5 --no-progress --reporter influx-file

          pkill hc && pkill holochain && pkill lair-keystore

      - name: Smoke test - write_validated
        run: |
          # Start a sandbox conductor and run it in the background
          nix develop .#ci -c bash -c "hc s clean && echo "1234" | hc s --piped create && echo "1234" | hc s --piped -f 8888 run &"

          # Run the scenario for 5 seconds
          RUST_LOG=info nix run .#write_validated -- --connection-string ws://localhost:8888 --duration 5 --no-progress --reporter influx-file

          pkill hc && pkill holochain && pkill lair-keystore
