[package]
name = "peerkit_hole_punch"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
anyhow = { workspace = true }
log = { workspace = true }
tokio = { workspace = true }

peerkit_wind_tunnel_runner = { workspace = true }

[lints]
workspace = true

# This key must be present for the happ builder to work,
# but it's empty since peerkit scenarios do not require dnas or happs.
[package.metadata]
